### PR TITLE
Added express-handlebars templating and view structure for handlebars

### PR DESCRIPTION
**Pull request by zolitch**
I prefer using Handlebars and have found the [express-handlebars](https://github.com/ericf/express-handlebars) package to be very useful as it handles layouts and partials quite nicely. I have basically just copied what was done for the swig template engine and just added in the extra middleware stuff for the handlebars layouts and partials to their respective app.js and express.js locations.

Tested with basic and mvc implementations.

### CODE REVIEW

**Comment by petecoop** [comment]
Hey, thanks for this. Not sure if you saw but there was an open issue for this open here #60.

It's looking pretty good so far, I've made a comment to do with blank lines. Btw because handlebars supports layouts you might as well move the header & footer into the layout to make it simpler, this is similar to the jade templates.

The test for the Basic generator is failing because you've put `'app/views/index.handlebars'` but it should be `'views/index.handlebars'`

**Comment by zolitch** [comment]
Hey.

I've made the changes you mentioned. I had thought originally to add the footer and header to the layout but figured it would break your convention. I didn't see the open issue either. Sorry. :-/ 

Ran the tests again and all passing.

**Comment by zolitch** [comment]
Erm, I'm a bit confused as to why the Travis build is still failing?

I get 61 tests passing locally...

**Comment by petecoop** [comment]
When testing locally I get the same output as Travis, try deleting your `test/temp` then running `npm test` again?

**Comment by zolitch** [comment]
Arg. I blame git. Wierd. Sorry about that. 

I have added it back in. The way it works as described in the repo for [express handlebars](https://www.npmjs.com/package/express-handlebars?__hstc=72727564.1ef51f94dbf99ea063bda98d19536a88.1419857170248.1420708183942.1420718994644.15&__hssc=72727564.1.1420718994644&__hsfp=1037958624), the layout is used as a master template. Each page in the site can then have header, footer etc in the layout. Partials are there if you need them to abstract and componentise your markup further.

**Comment by petecoop** [comment]
Published as 2.4.2

I see the logic with the partials, I use them often it just doesn't follow the other templates as I haven't provided a partials directory for them. I've decided to keep it for this however as there's a configuration value for the partials dir

**Comment by bradoyler** [comment]
:+1:

**Pull request merged**
