### PR TITLE
add buyan logger

### PR DESCRIPTION
**Pull request by zackexplosion**
It's better to have log level with this package.

### CODE REVIEW

**Comment by petecoop** [comment]
While it might be better, this generator has been based on the express-generator which still uses morgan. This could be added as an option?

**Comment by zackexplosion** [comment]
As far as I know about morgan it's only log HTTP request, but with bunyan you can make any logger for the app.

**Comment by petecoop** [comment]
Okay in this case then I think this needs to be added as an option, as discussed in #78 - although I've not had time to implement those.

**Comment by zackexplosion** [comment]
Sure, keep express  simply, but I think It's only available for gulp now.

**Pull request closed without merging**
